version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ai_organisms
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "4000:4000" # Exposes the Encore backend API
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/ai_organisms?sslmode=disable
      # This tells Encore to listen on all interfaces inside the container
      - ENCORE_LISTEN=0.0.0.0:4000

  frontend:
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80" # Exposes the Nginx server to the host on port 8080

volumes:
  postgres-data:
