# render.yaml
# This file configures the deployment on Render.com.
# Render will automatically detect this file and set up the services.

services:
  # 1. A PostgreSQL database for the backend
  - type: pserv
    name: ai-organism-db
    databaseName: ai_organisms
    user: admin
    plan: free # Note: free instances spin down after 15 minutes of inactivity.

  # 2. The backend service
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/placeholder/placeholder # Will be replaced by Render
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-organism-db
          property: connectionString
      - key: ENCORE_LISTEN
        value: 0.0.0.0:4000
      # For production, it's good practice to set this explicitly,
      # though Encore defaults to 'production' in most CI/hosting envs.
      - key: ENCORE_ENV
        value: production

  # 3. The frontend static site
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/placeholder/placeholder # Will be replaced by Render
    dockerfilePath: ./frontend/Dockerfile
    dockerBuildArgs:
      VITE_CLIENT_TARGET: ${{backend.url}} # Use the live URL of the backend service
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Set a health check path for the static site to ensure it's up
    healthCheckPath: /index.html
