name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Install backend dependencies
      run: cd backend && bun install --frozen-lockfile

    - name: Run backend tests
      run: cd backend && bun run test

  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Install frontend dependencies
      run: cd frontend && bun install --frozen-lockfile

    - name: Run frontend tests
      run: cd frontend && bun run test
